"""empty message

Revision ID: 8334aa956e83
Revises: dc5a1b9c360c
Create Date: 2018-04-16 15:36:12.726387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8334aa956e83'
down_revision = 'dc5a1b9c360c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
